<?php

namespace ZnBundle\Rbac\Domain\Services;

use ZnBundle\Rbac\Domain\Interfaces\ManagerServiceInterface;
use ZnBundle\Rbac\Domain\Interfaces\Repositories\ItemRepositoryInterface;
use ZnBundle\Rbac\Domain\Interfaces\Services\RoleServiceInterface;
use ZnBundle\Rbac\Domain\Interfaces\Repositories\RoleRepositoryInterface;
use ZnCore\Domain\Base\BaseCrudService;
use ZnCore\Domain\Interfaces\Entity\EntityIdInterface;
use ZnCore\Domain\Libs\Query;

class RoleService extends ItemService implements RoleServiceInterface
{

    protected $managerService;

    public function __construct(RoleRepositoryInterface $repository, ManagerServiceInterface $managerService)
    {
        $this->repository = $repository;
        $this->managerService = $managerService;
    }

    public function create($data): EntityIdInterface
    {
        //dd($data);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function oneByName(string $name, Query $query = null)
    {
        return $this->repository->oneByName($name, $query);
    }
}
